name: pos_mutama
description: "Aplikasi Kasir Offline untuk Toko Bahan Bangunan."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Database Lokal
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # State Management
  flutter_riverpod: ^2.4.9
  
  # Utilitas
  uuid: ^4.3.3
  intl: ^0.20.2 # Untuk format tanggal dan angka

  # Fitur
  mobile_scanner: ^7.0.1
  csv: ^6.0.0
  file_picker: ^10.1.9
  pdf: ^3.10.7
  printing: ^5.11.1
  
  share_plus: ^11.0.0              
  permission_handler: ^12.0.0+1

  cupertino_icons: ^1.0.2
  fl_chart: ^0.68.0
  file_saver: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generators
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true