name: pos_mutama
description: "Aplikasi Kasir Offline untuk Toko Bahan Bangunan."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Database Lokal
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # State Management
  flutter_riverpod: ^2.4.9
  
  # Utilitas
  uuid: ^4.3.3
  intl: ^0.18.1 # Untuk format tanggal dan angka

  # Fitur
  flutter_barcode_scanner: ^2.0.0
  csv: ^5.1.1
  file_picker: ^6.1.1
  pdf: ^3.10.7
  printing: ^5.11.1
  
  share_plus: ^7.2.2              
  permission_handler: ^11.3.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generators
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true